@startuml
!include style.puml
skinparam ArrowFontStyle plain

box "Initialization" UI_COLOR_T1
participant ":PersonListPanel" as PersonListPanel UI_COLOR
participant "displayCard:DisplayCard" as DisplayCard UI_COLOR
participant ":Person" as Person MODEL_COLOR
end box

create DisplayCard
PersonListPanel -> DisplayCard : DisplayCard(person)
activate DisplayCard

DisplayCard -> DisplayCard : setUpLabels(person)
activate DisplayCard


DisplayCard -> Person : getName()
activate Person
Person --> DisplayCard
deactivate Person
DisplayCard -> Person : getPhone()
activate Person
Person --> DisplayCard
deactivate Person
DisplayCard -> Person : getAddress()
activate Person
Person --> DisplayCard
deactivate Person
DisplayCard -> Person : getEmail()
activate Person
Person --> DisplayCard
deactivate Person
DisplayCard -> Person : getRemark()
activate Person
Person --> DisplayCard
deactivate Person
DisplayCard -> Person : getTags()
activate Person
Person --> DisplayCard
deactivate Person
DisplayCard -> Person : getDaysAvailable()
activate Person
Person -->DisplayCard
deactivate Person

DisplayCard -> Person : getBirthday()
activate Person
Person --> DisplayCard
deactivate Person
DisplayCard -> Person : getMoneyOwed()
activate Person
Person --> DisplayCard
deactivate Person

DisplayCard --> DisplayCard
deactivate DisplayCard

DisplayCard -> DisplayCard : setUpIcons()
activate DisplayCard
deactivate DisplayCard

DisplayCard -> DisplayCard : playAnimation()
activate DisplayCard
deactivate DisplayCard

DisplayCard --> PersonListPanel
deactivate DisplayCard
@enduml
