@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

abstract class Command
abstract class Filter
interface Predicate

left to right direction

skinparam groupInheritance 2

Command <|-- Filter

Filter <|-- FilterNameCommand
Filter <|-- FilterTagCommand
Filter <|-- FilterDayCommand
Filter --> "1" Predicate

PersonHasTagPredicate ..|> Predicate
NameContainsKeywordsPredicate ..|> Predicate
PersonAvailableOnDayPredicate ..|> Predicate

FilterNameCommand o--> "1" NameContainsKeywordsPredicate
FilterTagCommand o--> "1" PersonHasTagPredicate
FilterDayCommand o--> "1" PersonAvailableOnDayPredicate
@enduml
