@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

left to right direction

Class "{abstract}\nCommand" as Command
Class "{abstract}\nFilter" as  Filter
Class "<<interface>>\nPredicate" as Predicate

skinparam groupInheritance 2

Command <|-- Filter

Filter <|-- FilterNameCommand
Filter <|-- FilterTagCommand
Filter <|-- FilterDayCommand
Filter --> "1" Predicate

PersonHasTagPredicate ..|> Predicate
NameContainsKeywordsPredicate ..|> Predicate
PersonAvailableOnDayPredicate ..|> Predicate

FilterNameCommand o--> "1" NameContainsKeywordsPredicate
FilterTagCommand o--> "1" PersonHasTagPredicate
FilterDayCommand o--> "1" PersonAvailableOnDayPredicate
@enduml
