@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

start
: User enters a lend command;

: LendCommandParser parses the user input and checks if input is valid;

switch ()
case([the LendCommand is valid])
    : Creates a LendCommand which is executed by the LogicManager;
    switch()
    case([Index in range])
    : Updates target Person in FilterPersonList to have the updated amount owed;
    : Updates the FilterPersonList in the Model;
    case([else])
    : Throws an error;
    endswitch
case([else])
    : Throws an error;
endswitch
stop
@enduml
