title: "FriendFolio"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "newtonkoh/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji

